fixed contributions and repositories bug in sidebar of resume
ashutosh-rath02/git-re pull request #207
Opened 2024-05-31 07:11 UTC by atharvarekhawar

## Related Issue
None

## Description
There was a rendering bug in show contributions which is no more and the limit of repositories is increased to 6.

## Type of PR

- [X ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X ] I have performed a self-review of my code
- [X ] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Please add appropriate labels while merging, Thank you 😊.

2024-05-31 07:12 UTC, ashutosh-rath02 commented
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

2024-05-31 17:05 UTC, ashutosh-rath02 commented
@atharvarekhawar Can you share a video with the changes, it would be helpful?

2024-05-31 18:58 UTC, atharvarekhawar commented
> @atharvarekhawar Can you share a video with the changes, it would be helpful?


https://github.com/ashutosh-rath02/git-re/assets/113119063/ab20ecbf-f869-4fc2-a9a7-cfd7365795c4

@ashutosh-rath02 now there is no problem while changing show contributions count and contributions are rendered without any glitch , show repositories have been limited to 6 and if user inserts number larger than 6 , still  it shows 6 repos.

2024-06-01 04:04 UTC, ashutosh-rath02 requested changes

2024-06-01 04:04 UTC, ashutosh-rath02 commented on utils/resumeUtils.ts
> +
remove this

2024-06-01 04:05 UTC, ashutosh-rath02 commented
Can you explain me the bug again once coz I see only changes, where you changed limit to 5

2024-06-01 07:08 UTC, atharvarekhawar commented
> Can you explain me the bug again once coz I see only changes, where you changed limit to 6

The glitch of the contributions was not present when I pulled latest changes and started the application on my local machine , so I just changed the limit to 6.

@ashutosh-rath02

2024-06-01 07:11 UTC, atharvarekhawar commented on utils/resumeUtils.ts
> +
done with the changes @ashutosh-rath02

2024-06-02 06:07 UTC, atharvarekhawar commented
can you merge the code @ashutosh-rath02

2024-06-02 15:52 UTC, ashutosh-rath02 commented
This doesn't fix the problem as provided in the parent issue.

2024-06-02 16:00 UTC, atharvarekhawar commented
> This doesn't fix the problem as provided in the parent issue.

there is no bug at the current moment in the website which is similar to the parent issue

2024-06-03 11:20 UTC, merged

2024-07-02 18:40 UTC, ashutosh-rath02 reviewed
LGTM