Searchbar added
ashutosh-rath02/git-re pull request #376
Opened 2024-07-10 14:33 UTC by komal-agarwal5

## Related Issue
#365 
## Description
I have added search bar in leaderboard page to improve user experience

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
![Screenshot 2024-07-10 193729](https://github.com/ashutosh-rath02/git-re/assets/122633300/dc8ec48d-43f8-4fc9-96e4-a440d8f1c81d)
![Screenshot 2024-07-10 193741](https://github.com/ashutosh-rath02/git-re/assets/122633300/72c416f5-62d4-4e7e-9229-b86b1e8b1fd7)

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Sir can you please check if it is working now as previously i was facing issues in loading the page on my localhost?

2024-07-10 14:33 UTC, ashutosh-rath02 commented
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

2024-07-11 03:51 UTC, ashutosh-rath02 requested changes
@komal-agarwal5 can you please resolve these?

![image](https://github.com/ashutosh-rath02/git-re/assets/85403534/036a7422-41ba-4053-8a0f-488236d0b1e9)

2024-07-11 03:52 UTC, ashutosh-rath02 commented on app/leaderboard/page.tsx
> +                      href={${process.env.NEXT_PUBLIC_URL}/resume/${user.username}}
Why have you removed the ticks?

2024-07-11 11:18 UTC, komal-agarwal5 commented
Ok sir I will make the corrections soon

2024-07-11 19:19 UTC, komal-agarwal5 commented
https://github.com/user-attachments/assets/ce792001-c611-4121-8b62-304e121098b7

I have made the corrections, is it working now?
@ashutosh-rath02

2024-07-12 17:42 UTC, ashutosh-rath02 approved these changes
LGTM

2024-07-14 12:41 UTC, ashutosh-rath02 requested changes
@komal-agarwal5 If we search for a name in 2nd page we can't access it, you have to search from the db rather than from frontend directly.

2024-07-14 16:00 UTC, komal-agarwal5 commented
> @komal-agarwal5 If we search for a name in 2nd page we can't access it, you have to search from the db rather than from frontend directly.

Ok i will redo it accordingly

2024-07-15 14:23 UTC, ashutosh-rath02 commented
@komal-agarwal5 updates?

2024-07-15 18:25 UTC, komal-agarwal5 commented
> @komal-agarwal5 updates?

will complete by tomorrow eod

2024-07-16 17:03 UTC, komal-agarwal5 commented
> @komal-agarwal5 updates?

@ashutosh-rath02 

https://github.com/user-attachments/assets/3a3a1720-7c2b-4dc3-965e-01a0af108b26

This is the progress till now
I have integrated search from database instead of frontend and search function is working on same page as well as different page as i checked by adding 50 dummy datas
But the problem I am facing is when search is successful the user's rank is showing as 1 irrespective of its original rank
I have been trying to fix this but coudnt till now
So i request you to give me some more time to complete this

I have pushed the changes made till now ,you can check out if you want

2024-07-18 10:32 UTC, ashutosh-rath02 commented
Ok maybe @dhairyathedev can help.

2024-07-18 11:18 UTC, dhairyathedev commented
> Ok maybe @dhairyathedev can help.

Okay, I will look into it.

2024-07-18 16:11 UTC, dhairyathedev commented
@ashutosh-rath02 you can merge this PR. I will open another PR to fix this issue.

2024-07-18 16:36 UTC, merged

2024-07-18 16:50 UTC, ashutosh-rath02 commented
@all-contributor please add @komal-agarwal5 for code

2024-07-18 16:56 UTC, ashutosh-rath02 reviewed
LGTM