[Bug fixed]: Leaderboard badges malfunctioning in search results
ashutosh-rath02/git-re pull request #396
Opened 2024-07-19 16:04 UTC by dhairyathedev

Fixes #392

2024-07-19 16:04 UTC, ashutosh-rath02 commented
Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. In the meantime, please ensure that your changes align with our [CONTRIBUTING.md](https://github.com/ashutosh-rath02/git-re/blob/main/CONTRIBUTING.md). If there are any specific instructions or feedback regarding your PR, we'll provide them here. Thanks again for your contribution! 😊

2024-07-20 05:02 UTC, ashutosh-rath02 commented on app/leaderboard/page.tsx
> +              {/* ... (skeleton loading code remains the same) ... */}
What's this?

2024-07-20 05:02 UTC, ashutosh-rath02 requested changes
Complete the code

2024-07-20 05:09 UTC, dhairyathedev commented on app/leaderboard/page.tsx
> +              {/* ... (skeleton loading code remains the same) ... */}
Resolved @ashutosh-rath02

2024-07-20 05:43 UTC, ashutosh-rath02 approved these changes
LGTM 🥊

2024-07-21 09:49 UTC, merged