major: redesigned Navbar and Footer
ashutosh-rath02/git-re pull request #78
Opened 2024-05-11 18:27 UTC by dhairyathedev

- Redesigned the navbar
- Redesign the footer

2024-05-11 18:33 UTC, dhairyathedev commented
@ashutosh-rath02 here's the changes in the UI.

Demonstration Video: https://youtu.be/3UvRmTUcETQ

2024-05-12 03:32 UTC, ashutosh-rath02 commented
Hey @dhairyathedev awesome work there, just the logo on the footer and navbar needs to be changed. Keep it as it is now

2024-05-12 04:34 UTC, dhairyathedev commented
> Hey @dhairyathedev awesome work there, just the logo on the footer and navbar needs to be changed. Keep it as it is now


Hey @ashutosh-rath02, you mean to keep the current logo with black color, right?
<img width="182" alt="Screenshot 2024-05-12 at 10 04 41 AM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/dcb20620-5c37-4cc1-9e3b-da9d8c94b4d1">

2024-05-12 05:01 UTC, dhairyathedev commented
Hey @ashutosh-rath02 , reverted to old logo.
<br />
![image](https://github.com/ashutosh-rath02/git-re/assets/65452005/b48f84f6-14f4-4e35-955d-e8cd06ff9417)

2024-05-12 05:02 UTC, dhairyathedev commented
Please review and merge the PR.

2024-05-12 05:06 UTC, ashutosh-rath02 requested changes

2024-05-12 05:06 UTC, ashutosh-rath02 commented on components/AuthButton.tsx
> +      className={`animate-shimmer h-10 ${className}`} // Add className prop to the Button
Remove comments

2024-05-12 05:06 UTC, ashutosh-rath02 commented on components/footer.tsx
> +          </h1> */}
remove unwanted comments

2024-05-12 05:06 UTC, ashutosh-rath02 commented on components/footer.tsx
> -          &copy; {currentYear} Made with 🤯 by Ashutosh Rath
Keep this line

2024-05-12 05:06 UTC, ashutosh-rath02 commented on components/footer.tsx
> +          </div>
We don't have these sections. Please remove them

2024-05-12 05:06 UTC, ashutosh-rath02 commented on components/navbar.tsx
> +        </h1> */}
Remove comments

2024-05-12 05:06 UTC, ashutosh-rath02 commented on components/navbar.tsx
> +          className="text-[3C3C3C] hover:text-primary font-semibold transition sm:block hidden"
Put the color in `tailwind.config.js` and use from there

2024-05-12 05:09 UTC, ashutosh-rath02 commented
![image](https://github.com/ashutosh-rath02/git-re/assets/85403534/4737d4de-ec1f-4822-88c8-3d3f962319b3)
Hey @dhairyathedev the gaps on both side is too small which is looking odd, keep the gaps use `max-w-` to adjust the width. Check the present website to see gaps on both sides, 
Do the same for footer.

2024-05-12 05:10 UTC, ashutosh-rath02 commented
@dhairyathedev pull the recent changes once then work on it... as some changes have been introduced, I want to check how it looks with the whole website.

2024-05-12 05:21 UTC, dhairyathedev commented
> ![image](https://private-user-images.githubusercontent.com/85403534/329826950-4737d4de-ec1f-4822-88c8-3d3f962319b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0OTE0NjMsIm5iZiI6MTcxNTQ5MTE2MywicGF0aCI6Ii84NTQwMzUzNC8zMjk4MjY5NTAtNDczN2Q0ZGUtZWMxZi00ODIyLTg4YzgtM2QzZjk2MjMxOWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA1MTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzY2RmOWJkNDRhZDUyNWU3ODJjYzY2NGJhOTBhNTY0MWJkMzQzMmE5Y2ZkMTJiYTRiMjQyMzA5ODVjMDdmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rZvvxLu8_CXz93kx_TRC7KAQSX6GDP5P43H4IiL38wI) Hey @dhairyathedev the gaps on both side is too small which is looking odd, keep the gaps use `max-w-` to adjust the width. Check the present website to see gaps on both sides, Do the same for footer.

I have kept the same width as the current site, and the padding and margin are proper on my device with proper gaps on each side.

<img width="1680" alt="Screenshot 2024-05-12 at 10 50 41 AM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/801e3564-37e2-469e-96b2-53887394623b">

2024-05-12 05:24 UTC, ashutosh-rath02 commented
@dhairyathedev You can check the preview

2024-05-12 05:39 UTC, dhairyathedev commented
> @dhairyathedev You can check the preview https://git-re-git-fork-dhairyathedev-main-lucif3rins-projects.vercel.app/ Check for larger screens maybe

I need access required to view the preview deployment. I have sent access request, please approve. @ashutosh-rath02

2024-05-12 05:41 UTC, ashutosh-rath02 commented
Done

2024-05-12 05:48 UTC, dhairyathedev commented
> Done

@ashutosh-rath02 
<img width="843" alt="Screenshot 2024-05-12 at 11 17 38 AM" src="https://github.com/ashutosh-rath02/git-re/assets/65452005/4016dfc8-211d-4128-bf55-9c85ffc14d3f">

2024-05-12 05:49 UTC, dhairyathedev commented
> ![image](https://private-user-images.githubusercontent.com/85403534/329826950-4737d4de-ec1f-4822-88c8-3d3f962319b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0OTMxNDEsIm5iZiI6MTcxNTQ5Mjg0MSwicGF0aCI6Ii84NTQwMzUzNC8zMjk4MjY5NTAtNDczN2Q0ZGUtZWMxZi00ODIyLTg4YzgtM2QzZjk2MjMxOWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA1NDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOTA0ZDE4ZTE3OTkxNWIzMjgzNDA3OTQyYjg0ZDVhOGU1Y2I5MTdiOGU1YWNkZWRjODQ1YzAzNWEzZDJlMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7KCZXoQoUTUHzNcqv9W0GNrD41_zhjMq9lYrMgStwxg) Hey @dhairyathedev the gaps on both side is too small which is looking odd, keep the gaps use `max-w-` to adjust the width. Check the present website to see gaps on both sides, Do the same for footer.

I have updated the mentioned changes and the gap issue. Please check if it still exists.

2024-05-12 05:55 UTC, ashutosh-rath02 commented
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> Name	Status	Preview	Comments	Updated (UTC)
> **git-re**	🔄 Building ([Inspect](https://vercel.com/lucif3rins-projects/git-re/3innipjvTkktk11xR5dScQgvXNpW))	[Visit Preview](https://vercel.live/open-feedback/git-re-git-fork-dhairyathedev-main-lucif3rins-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1)	💬 [**Add feedback**](https://vercel.live/open-feedback/git-re-git-fork-dhairyathedev-main-lucif3rins-projects.vercel.app?via=pr-comment-feedback-link)	May 12, 2024 5:52am

@dhairyathedev Can you check the review now?

2024-05-12 05:57 UTC, dhairyathedev commented
> > **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> > Name	Status	Preview	Comments	Updated (UTC)
> > **git-re**	🔄 Building ([Inspect](https://vercel.com/lucif3rins-projects/git-re/3innipjvTkktk11xR5dScQgvXNpW))	[Visit Preview](https://vercel.live/open-feedback/git-re-git-fork-dhairyathedev-main-lucif3rins-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1)	💬 [**Add feedback**](https://vercel.live/open-feedback/git-re-git-fork-dhairyathedev-main-lucif3rins-projects.vercel.app?via=pr-comment-feedback-link)	May 12, 2024 5:52am
> 
> @dhairyathedev Can you check the review now?

Yes I can see the preview

2024-05-12 05:59 UTC, ashutosh-rath02 commented
Let's connect over discord https://discordapp.com/users/519818032973873152

2024-05-12 06:09 UTC, merged